### ISSUE TITLE
What is the booster speed?

### ISSUE THREAD

**Issue by adsaadsa** [faceslog/SteamPlaytimeBooster#2]
I'm sorry my English is bad
I have a question. What is the speed of the booster?
This refers to a speed where just one hour of playtime on Steam can reach 2 hours.

**Comment by faceslog** [comment]
The program is primarily used to increase gametime on an account by running in the background. While it operates, it simulates active play and records the time accordingly. Booster for steam adheres to the principle of 1 hour of runtime equaling 1 hour of playtime. However it is designed to be lightweight, running efficiently in the background without significantly impacting your computer's performance or consuming resources like a full game would.
